/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prueba_diseño;

import clases_conexion.BDConexion;
import java.sql.*;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class GestionUsuarios extends javax.swing.JFrame {

    DefaultTableModel usuario = new DefaultTableModel();
    
    public GestionUsuarios() {
        initComponents();
        setSize(650, 500);
        setLocationRelativeTo(null);
        setTitle("Modificar Cuenta Usuario");
        
        Estilos boton = new Estilos();
        boton.btnSalir(btn_salir);
    
        try {
            Connection cn2 = BDConexion.conectar();
            PreparedStatement pst2 = cn2.prepareStatement(
                    "SELECT `id_usuario`, `nombre_usuario`, `contraseña` "
                    + "FROM `cuentausuario`");
            ResultSet rs2 = pst2.executeQuery();

            jTable_usuarios= new JTable(usuario);
            jScrollPane_usuario.setViewportView(jTable_usuarios);

            usuario.addColumn("ID Usurio");
            usuario.addColumn("Nombres Usuario");
            usuario.addColumn("Contraseña");

            while (rs2.next()) {
                Object[] filas = new Object[3];

                for (int i = 0; i < 3; i++) {
                    filas[i] = rs2.getObject(i + 1);
                }
                usuario.addRow(filas);
            }
            cn2.close();

        } catch (SQLException e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "Error al mostrar informacion Contactar al abministrador de la base de datos");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        panel_salir = new prueba_diseño.PanelRound();
        btn_salir = new javax.swing.JLabel();
        panelRound1 = new prueba_diseño.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane_usuario = new javax.swing.JScrollPane();
        jTable_usuarios = new javax.swing.JTable();
        panel_modificar = new prueba_diseño.PanelRound();
        btn_modificar = new javax.swing.JLabel();
        panel_eliminar = new prueba_diseño.PanelRound();
        btn_eliminar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(16, 23, 39));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_salir.setBackground(new java.awt.Color(255, 255, 255));
        panel_salir.setRoundBottomLeft(25);
        panel_salir.setRoundBottomRight(25);
        panel_salir.setRoundTopLeft(25);
        panel_salir.setRoundTopRight(25);
        panel_salir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_salirMouseExited(evt);
            }
        });
        panel_salir.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanel1.add(panel_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 50, 50));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(25);
        panelRound1.setRoundBottomRight(25);
        panelRound1.setRoundTopLeft(25);
        panelRound1.setRoundTopRight(25);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(16, 23, 39));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion de Usuarios");
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 200, -1));

        jTable_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Maria2323", "123456", "ACTIVO"},
                {"2", "Pedro_j", "223344", "INACTIVO"},
                {"3", "Jose1525", "987654", "ACTIVO"},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre Usuario", "Contraseña", "Estado"
            }
        ));
        jScrollPane_usuario.setViewportView(jTable_usuarios);

        panelRound1.add(jScrollPane_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 60, 450, 265));

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 500, 350));

        panel_modificar.setBackground(new java.awt.Color(81, 77, 167));
        panel_modificar.setRoundBottomLeft(25);
        panel_modificar.setRoundBottomRight(25);
        panel_modificar.setRoundTopLeft(25);
        panel_modificar.setRoundTopRight(25);
        panel_modificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_modificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos32px/editar.png"))); // NOI18N
        btn_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_modificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_modificarMouseExited(evt);
            }
        });
        panel_modificar.add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 70, 70));

        jPanel1.add(panel_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 70, 70));

        panel_eliminar.setBackground(new java.awt.Color(81, 77, 167));
        panel_eliminar.setRoundBottomLeft(25);
        panel_eliminar.setRoundBottomRight(25);
        panel_eliminar.setRoundTopLeft(25);
        panel_eliminar.setRoundTopRight(25);
        panel_eliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_eliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos32px/eliminar.png"))); // NOI18N
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseExited(evt);
            }
        });
        panel_eliminar.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 70, 70));

        jPanel1.add(panel_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 70, 70));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gestion de Usuarios");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 40, 250, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Eliminar");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 375, -1, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Modificar");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 225, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_modificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarMouseEntered
        panel_modificar.setBackground(new Color(80,5,5));
    }//GEN-LAST:event_btn_modificarMouseEntered

    private void btn_modificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarMouseExited
        panel_modificar.setBackground(new Color(81,77,167));
    }//GEN-LAST:event_btn_modificarMouseExited

    private void btn_eliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseEntered
        panel_eliminar.setBackground(new Color(80,5,5));
    }//GEN-LAST:event_btn_eliminarMouseEntered

    private void btn_eliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseExited
        panel_eliminar.setBackground(new Color(81,77,167));
    }//GEN-LAST:event_btn_eliminarMouseExited

    private void btn_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseEntered
        panel_salir.setBackground(new Color(14,120,220));
    }//GEN-LAST:event_btn_salirMouseEntered

    private void btn_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseExited
        panel_salir.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_salirMouseExited

    private void btn_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseClicked
        dispose();
        new MenuAdmin().setVisible(true);
    }//GEN-LAST:event_btn_salirMouseClicked

    private void btn_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarMouseClicked
        dispose();
        new ModificarUsuario().setVisible(true);
    }//GEN-LAST:event_btn_modificarMouseClicked

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
        JOptionPane.showInputDialog(null, "", DISPOSE_ON_CLOSE);
        JOptionPane.showInputDialog(null, "");
    }//GEN-LAST:event_btn_eliminarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_eliminar;
    private javax.swing.JLabel btn_modificar;
    private javax.swing.JLabel btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane_usuario;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_usuarios;
    private prueba_diseño.PanelRound panelRound1;
    private prueba_diseño.PanelRound panel_eliminar;
    private prueba_diseño.PanelRound panel_modificar;
    private prueba_diseño.PanelRound panel_salir;
    // End of variables declaration//GEN-END:variables
}
