package prueba_diseño;

import java.awt.Color;


public class MenuAdmin extends javax.swing.JFrame {

    
   
    public MenuAdmin() {
        initComponents();
        setTitle("Menu Administrador");
        setSize(400, 300);
        setLocationRelativeTo(null);
        setResizable(false);
        
        Estilos boton = new Estilos();
        boton.btnSalir(btn_salir);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_gestionar = new prueba_diseño.PanelRound();
        btn_gestionar = new javax.swing.JLabel();
        panel_salir = new prueba_diseño.PanelRound();
        btn_salir = new javax.swing.JLabel();
        panel_crear = new prueba_diseño.PanelRound();
        btn_crear = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(16, 23, 39));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu de Opciones");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 220, -1));

        panel_gestionar.setBackground(new java.awt.Color(81, 77, 167));
        panel_gestionar.setRoundBottomLeft(25);
        panel_gestionar.setRoundBottomRight(25);
        panel_gestionar.setRoundTopLeft(25);
        panel_gestionar.setRoundTopRight(25);
        panel_gestionar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_gestionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_gestionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos64px/proceso.png"))); // NOI18N
        btn_gestionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_gestionarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_gestionarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_gestionarMouseExited(evt);
            }
        });
        panel_gestionar.add(btn_gestionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 100));

        jPanel1.add(panel_gestionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 80, 100, 100));

        panel_salir.setBackground(new java.awt.Color(255, 255, 255));
        panel_salir.setRoundBottomLeft(25);
        panel_salir.setRoundBottomRight(25);
        panel_salir.setRoundTopLeft(25);
        panel_salir.setRoundTopRight(25);
        panel_salir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_salirMouseExited(evt);
            }
        });
        panel_salir.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanel1.add(panel_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 50, 50));

        panel_crear.setBackground(new java.awt.Color(81, 77, 167));
        panel_crear.setRoundBottomLeft(25);
        panel_crear.setRoundBottomRight(25);
        panel_crear.setRoundTopLeft(25);
        panel_crear.setRoundTopRight(25);
        panel_crear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_crear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos64px/nuevo-usuario.png"))); // NOI18N
        btn_crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_crearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_crearMouseExited(evt);
            }
        });
        panel_crear.add(btn_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 100));

        jPanel1.add(panel_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 80, 100, 100));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Crear Usuario");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 180, 100, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gestionar Usuaio");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 180, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_crearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearMouseEntered
        panel_crear.setBackground(new Color(80,5,5));
    }//GEN-LAST:event_btn_crearMouseEntered

    private void btn_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseEntered
        panel_salir.setBackground(new Color(14,120,220));
    }//GEN-LAST:event_btn_salirMouseEntered

    private void btn_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseExited
         panel_salir.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_salirMouseExited

    private void btn_crearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearMouseExited
        panel_crear.setBackground(new Color(81,77,167));
    }//GEN-LAST:event_btn_crearMouseExited

    private void btn_gestionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_gestionarMouseEntered
        panel_gestionar.setBackground(new Color(80,5,5));
    }//GEN-LAST:event_btn_gestionarMouseEntered

    private void btn_gestionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_gestionarMouseExited
        panel_gestionar.setBackground(new Color(81,77,167));
    }//GEN-LAST:event_btn_gestionarMouseExited

    private void btn_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseClicked
        dispose();
        new AccesoAdmin().setVisible(true);
    }//GEN-LAST:event_btn_salirMouseClicked

    private void btn_crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearMouseClicked
        dispose();
        new CrearUsuario().setVisible(true);
    }//GEN-LAST:event_btn_crearMouseClicked

    private void btn_gestionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_gestionarMouseClicked
        dispose();
        new GestionUsuarios().setVisible(true);
    }//GEN-LAST:event_btn_gestionarMouseClicked
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_crear;
    private javax.swing.JLabel btn_gestionar;
    private javax.swing.JLabel btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private prueba_diseño.PanelRound panel_crear;
    private prueba_diseño.PanelRound panel_gestionar;
    private prueba_diseño.PanelRound panel_salir;
    // End of variables declaration//GEN-END:variables
}
