package prueba_diseño;

import clases_conexion.BDConexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class ModificarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form ModificarUsuario
     */
    public ModificarUsuario() {
        initComponents();
        setSize(500, 400);
        setLocationRelativeTo(null);
        
        Estilos boton = new Estilos();
        boton.btnSalir(btn_salir);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_modificar_usuario = new prueba_diseño.PanelRound();
        btn_modificar_usuario = new javax.swing.JLabel();
        panel_salir = new prueba_diseño.PanelRound();
        btn_salir = new javax.swing.JLabel();
        panelRound4 = new prueba_diseño.PanelRound();
        txt_usuario = new javax.swing.JTextField();
        panelRound5 = new prueba_diseño.PanelRound();
        txt_pass_confirm = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelRound6 = new prueba_diseño.PanelRound();
        txt_pass = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(16, 23, 39));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modificar Usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 200, -1));

        panel_modificar_usuario.setBackground(new java.awt.Color(81, 77, 167));
        panel_modificar_usuario.setRoundBottomLeft(25);
        panel_modificar_usuario.setRoundBottomRight(25);
        panel_modificar_usuario.setRoundTopLeft(25);
        panel_modificar_usuario.setRoundTopRight(25);
        panel_modificar_usuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_modificar_usuario.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_modificar_usuario.setForeground(new java.awt.Color(255, 255, 255));
        btn_modificar_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_modificar_usuario.setText("Modificar Usuario");
        btn_modificar_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificar_usuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_modificar_usuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_modificar_usuarioMouseExited(evt);
            }
        });
        panel_modificar_usuario.add(btn_modificar_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        jPanel1.add(panel_modificar_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 200, 40));

        panel_salir.setBackground(new java.awt.Color(255, 255, 255));
        panel_salir.setRoundBottomLeft(25);
        panel_salir.setRoundBottomRight(25);
        panel_salir.setRoundTopLeft(25);
        panel_salir.setRoundTopRight(25);
        panel_salir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_salirMouseExited(evt);
            }
        });
        panel_salir.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanel1.add(panel_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 50, 50));

        panelRound4.setBackground(new java.awt.Color(204, 204, 204));
        panelRound4.setRoundBottomLeft(25);
        panelRound4.setRoundBottomRight(25);
        panelRound4.setRoundTopLeft(25);
        panelRound4.setRoundTopRight(25);
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_usuario.setBackground(new java.awt.Color(204, 204, 204));
        txt_usuario.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(16, 23, 39));
        txt_usuario.setBorder(null);
        panelRound4.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 30));

        jPanel1.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 200, 30));

        panelRound5.setBackground(new java.awt.Color(204, 204, 204));
        panelRound5.setRoundBottomLeft(25);
        panelRound5.setRoundBottomRight(25);
        panelRound5.setRoundTopLeft(25);
        panelRound5.setRoundTopRight(25);
        panelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_pass_confirm.setBackground(new java.awt.Color(204, 204, 204));
        txt_pass_confirm.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txt_pass_confirm.setForeground(new java.awt.Color(16, 23, 39));
        txt_pass_confirm.setBorder(null);
        panelRound5.add(txt_pass_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 30));

        jPanel1.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 200, 30));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre Usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirmar Contraseña");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        panelRound6.setBackground(new java.awt.Color(204, 204, 204));
        panelRound6.setRoundBottomLeft(25);
        panelRound6.setRoundBottomRight(25);
        panelRound6.setRoundTopLeft(25);
        panelRound6.setRoundTopRight(25);
        panelRound6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_pass.setBackground(new java.awt.Color(204, 204, 204));
        txt_pass.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txt_pass.setForeground(new java.awt.Color(16, 23, 39));
        txt_pass.setBorder(null);
        panelRound6.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 30));

        jPanel1.add(panelRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 200, 30));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nueva Contraseña");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_modificar_usuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificar_usuarioMouseEntered
        panel_modificar_usuario.setBackground(new Color(80,5,5));
    }//GEN-LAST:event_btn_modificar_usuarioMouseEntered

    private void btn_modificar_usuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificar_usuarioMouseExited
        panel_modificar_usuario.setBackground(new Color(81,77,167));
    }//GEN-LAST:event_btn_modificar_usuarioMouseExited

    private void btn_modificar_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificar_usuarioMouseClicked
        String usuario = txt_usuario.getText().trim();
        String pass = txt_pass.getText().trim();
        
        if (!usuario.equals("")) {
             try {
                Connection cn = BDConexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "update cuentausuario set nombre_usuario=?, contraseña=? "
                        + "where nombre_usuario = '" + usuario + "'");

                pst.setString(1, usuario);
                pst.setString(2, pass);

                pst.executeUpdate();
                cn.close();

                JOptionPane.showMessageDialog(null, "Modificacion correcta.");
                this.dispose();

            } catch (SQLException e) {
                System.err.println("Error en Modificar Usuario. " + e);
                JOptionPane.showMessageDialog(null, "¡¡ERROR al Modificar Usuario!!, contacte al administrador.");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debes de llenar el campo usuario.");
        }
        
        
       
    }//GEN-LAST:event_btn_modificar_usuarioMouseClicked

    private void btn_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseEntered
        panel_salir.setBackground(new Color(14,120,220));
    }//GEN-LAST:event_btn_salirMouseEntered

    private void btn_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseExited
        panel_salir.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_salirMouseExited

    private void btn_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseClicked
        dispose();
        new GestionUsuarios().setVisible(true);
    }//GEN-LAST:event_btn_salirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_modificar_usuario;
    private javax.swing.JLabel btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private prueba_diseño.PanelRound panelRound4;
    private prueba_diseño.PanelRound panelRound5;
    private prueba_diseño.PanelRound panelRound6;
    private prueba_diseño.PanelRound panel_modificar_usuario;
    private prueba_diseño.PanelRound panel_salir;
    private javax.swing.JTextField txt_pass;
    private javax.swing.JTextField txt_pass_confirm;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
