package prueba_diseño;

import java.awt.Color;

/**
 *
 * @author usuario
 */
public class NuevoProveedor extends javax.swing.JFrame {

    /**
     * Creates new form NuevoProveedor
     */
    public NuevoProveedor() {
        initComponents();
        setSize(650, 700);
        setLocationRelativeTo(null);

        Estilos boton = new Estilos();
        boton.btnSalir(btn_salir);

        Estilos boton2 = new Estilos();
        boton2.btnSalir(btn_salir2);

        Estilos icon = new Estilos();
        icon.iconoPrincipal(icon_principal, "src/iconos32px_azul/mensajero.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_juridico = new javax.swing.JPanel();
        panelRound16 = new prueba_diseño.PanelRound();
        panelRound17 = new prueba_diseño.PanelRound();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panelRound18 = new prueba_diseño.PanelRound();
        panelRound19 = new prueba_diseño.PanelRound();
        jLabel16 = new javax.swing.JLabel();
        panelRound20 = new prueba_diseño.PanelRound();
        panel_registrar_juridico = new prueba_diseño.PanelRound();
        btn_registrar_juridico = new javax.swing.JLabel();
        panel_salir2 = new prueba_diseño.PanelRound();
        btn_salir2 = new javax.swing.JLabel();
        jPanel_natural = new javax.swing.JPanel();
        panel_salir = new prueba_diseño.PanelRound();
        btn_salir = new javax.swing.JLabel();
        panelRound3 = new prueba_diseño.PanelRound();
        jTextField16 = new javax.swing.JTextField();
        panelRound4 = new prueba_diseño.PanelRound();
        jTextField7 = new javax.swing.JTextField();
        panelRound5 = new prueba_diseño.PanelRound();
        jTextField14 = new javax.swing.JTextField();
        panelRound8 = new prueba_diseño.PanelRound();
        jTextField12 = new javax.swing.JTextField();
        panelRound9 = new prueba_diseño.PanelRound();
        jTextField13 = new javax.swing.JTextField();
        panelRound10 = new prueba_diseño.PanelRound();
        jTextField15 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panel_registrar_natural = new prueba_diseño.PanelRound();
        btn_registrar_natural = new javax.swing.JLabel();
        jPanel_cabecera = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        panelRound1 = new prueba_diseño.PanelRound();
        icon_principal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_juridico.setBackground(new java.awt.Color(16, 23, 39));
        jPanel_juridico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound16.setBackground(new java.awt.Color(204, 204, 204));
        panelRound16.setRoundBottomLeft(25);
        panelRound16.setRoundBottomRight(25);
        panelRound16.setRoundTopLeft(25);
        panelRound16.setRoundTopRight(25);
        panelRound16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel_juridico.add(panelRound16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 250, 40));

        panelRound17.setBackground(new java.awt.Color(204, 204, 204));
        panelRound17.setRoundBottomLeft(25);
        panelRound17.setRoundBottomRight(25);
        panelRound17.setRoundTopLeft(25);
        panelRound17.setRoundTopRight(25);
        panelRound17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel_juridico.add(panelRound17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 250, 40));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Correo");
        jPanel_juridico.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cedula o Rif");
        jPanel_juridico.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nombre Empresa");
        jPanel_juridico.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Direccion");
        jPanel_juridico.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        panelRound18.setBackground(new java.awt.Color(204, 204, 204));
        panelRound18.setRoundBottomLeft(25);
        panelRound18.setRoundBottomRight(25);
        panelRound18.setRoundTopLeft(25);
        panelRound18.setRoundTopRight(25);
        panelRound18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel_juridico.add(panelRound18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 250, 40));

        panelRound19.setBackground(new java.awt.Color(204, 204, 204));
        panelRound19.setRoundBottomLeft(25);
        panelRound19.setRoundBottomRight(25);
        panelRound19.setRoundTopLeft(25);
        panelRound19.setRoundTopRight(25);
        panelRound19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel_juridico.add(panelRound19, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 250, 40));

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Telefono");
        jPanel_juridico.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        panelRound20.setBackground(new java.awt.Color(204, 204, 204));
        panelRound20.setRoundBottomLeft(25);
        panelRound20.setRoundBottomRight(25);
        panelRound20.setRoundTopLeft(25);
        panelRound20.setRoundTopRight(25);
        panelRound20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel_juridico.add(panelRound20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 250, 40));

        panel_registrar_juridico.setBackground(new java.awt.Color(81, 77, 167));
        panel_registrar_juridico.setRoundBottomLeft(25);
        panel_registrar_juridico.setRoundBottomRight(25);
        panel_registrar_juridico.setRoundTopLeft(25);
        panel_registrar_juridico.setRoundTopRight(25);
        panel_registrar_juridico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_registrar_juridico.setBackground(new java.awt.Color(16, 23, 39));
        btn_registrar_juridico.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_registrar_juridico.setForeground(new java.awt.Color(255, 255, 255));
        btn_registrar_juridico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_registrar_juridico.setText("Registrar");
        btn_registrar_juridico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_registrar_juridicoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_registrar_juridicoMouseExited(evt);
            }
        });
        panel_registrar_juridico.add(btn_registrar_juridico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 50));

        jPanel_juridico.add(panel_registrar_juridico, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 200, 50));

        panel_salir2.setBackground(new java.awt.Color(255, 255, 255));
        panel_salir2.setRoundBottomLeft(25);
        panel_salir2.setRoundBottomRight(25);
        panel_salir2.setRoundTopLeft(25);
        panel_salir2.setRoundTopRight(25);
        panel_salir2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_salir2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_salir2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salir2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_salir2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_salir2MouseExited(evt);
            }
        });
        panel_salir2.add(btn_salir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanel_juridico.add(panel_salir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 50, 50));

        getContentPane().add(jPanel_juridico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 650, 600));

        jPanel_natural.setBackground(new java.awt.Color(16, 23, 39));
        jPanel_natural.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_salir.setBackground(new java.awt.Color(255, 255, 255));
        panel_salir.setRoundBottomLeft(25);
        panel_salir.setRoundBottomRight(25);
        panel_salir.setRoundTopLeft(25);
        panel_salir.setRoundTopRight(25);
        panel_salir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_salirMouseExited(evt);
            }
        });
        panel_salir.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanel_natural.add(panel_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 50, 50));

        panelRound3.setBackground(new java.awt.Color(204, 204, 204));
        panelRound3.setRoundBottomLeft(25);
        panelRound3.setRoundBottomRight(25);
        panelRound3.setRoundTopLeft(25);
        panelRound3.setRoundTopRight(25);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField16.setBackground(new java.awt.Color(204, 204, 204));
        jTextField16.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTextField16.setForeground(new java.awt.Color(0, 0, 0));
        jTextField16.setBorder(null);
        panelRound3.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 220, 40));

        jPanel_natural.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 340, 250, 40));

        panelRound4.setBackground(new java.awt.Color(204, 204, 204));
        panelRound4.setRoundBottomLeft(25);
        panelRound4.setRoundBottomRight(25);
        panelRound4.setRoundTopLeft(25);
        panelRound4.setRoundTopRight(25);
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField7.setBackground(new java.awt.Color(204, 204, 204));
        jTextField7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(0, 0, 0));
        jTextField7.setBorder(null);
        panelRound4.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 220, 40));

        jPanel_natural.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 100, 250, 40));

        panelRound5.setBackground(new java.awt.Color(204, 204, 204));
        panelRound5.setRoundBottomLeft(25);
        panelRound5.setRoundBottomRight(25);
        panelRound5.setRoundTopLeft(25);
        panelRound5.setRoundTopRight(25);
        panelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField14.setBackground(new java.awt.Color(204, 204, 204));
        jTextField14.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(0, 0, 0));
        jTextField14.setBorder(null);
        panelRound5.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 220, 40));

        jPanel_natural.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 220, 250, 40));

        panelRound8.setBackground(new java.awt.Color(204, 204, 204));
        panelRound8.setRoundBottomLeft(25);
        panelRound8.setRoundBottomRight(25);
        panelRound8.setRoundTopLeft(25);
        panelRound8.setRoundTopRight(25);
        panelRound8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField12.setBackground(new java.awt.Color(204, 204, 204));
        jTextField12.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(0, 0, 0));
        jTextField12.setBorder(null);
        panelRound8.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 220, 40));

        jPanel_natural.add(panelRound8, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 100, 250, 40));

        panelRound9.setBackground(new java.awt.Color(204, 204, 204));
        panelRound9.setRoundBottomLeft(25);
        panelRound9.setRoundBottomRight(25);
        panelRound9.setRoundTopLeft(25);
        panelRound9.setRoundTopRight(25);
        panelRound9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField13.setBackground(new java.awt.Color(204, 204, 204));
        jTextField13.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(0, 0, 0));
        jTextField13.setBorder(null);
        panelRound9.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 220, 40));

        jPanel_natural.add(panelRound9, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 220, 250, 40));

        panelRound10.setBackground(new java.awt.Color(204, 204, 204));
        panelRound10.setRoundBottomLeft(25);
        panelRound10.setRoundBottomRight(25);
        panelRound10.setRoundTopLeft(25);
        panelRound10.setRoundTopRight(25);
        panelRound10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField15.setBackground(new java.awt.Color(204, 204, 204));
        jTextField15.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(0, 0, 0));
        jTextField15.setBorder(null);
        panelRound10.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 220, 40));

        jPanel_natural.add(panelRound10, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 340, 250, 40));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");
        jPanel_natural.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido");
        jPanel_natural.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Documento");
        jPanel_natural.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Direccion");
        jPanel_natural.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Telefono");
        jPanel_natural.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Correo");
        jPanel_natural.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 310, -1, -1));

        panel_registrar_natural.setBackground(new java.awt.Color(81, 77, 167));
        panel_registrar_natural.setRoundBottomLeft(25);
        panel_registrar_natural.setRoundBottomRight(25);
        panel_registrar_natural.setRoundTopLeft(25);
        panel_registrar_natural.setRoundTopRight(25);
        panel_registrar_natural.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_registrar_natural.setBackground(new java.awt.Color(16, 23, 39));
        btn_registrar_natural.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_registrar_natural.setForeground(new java.awt.Color(255, 255, 255));
        btn_registrar_natural.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_registrar_natural.setText("Registrar");
        btn_registrar_natural.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_registrar_naturalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_registrar_naturalMouseExited(evt);
            }
        });
        panel_registrar_natural.add(btn_registrar_natural, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 50));

        jPanel_natural.add(panel_registrar_natural, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 450, 200, 50));

        getContentPane().add(jPanel_natural, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 650, 600));

        jPanel_cabecera.setBackground(new java.awt.Color(16, 23, 39));
        jPanel_cabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Proveedor");
        jPanel_cabecera.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 250, 50));

        jComboBox1.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(16, 23, 39));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proveedor Natural", "Proveedor Juridico" }));
        jPanel_cabecera.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 120, -1));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(25);
        panelRound1.setRoundBottomRight(25);
        panelRound1.setRoundTopLeft(25);
        panelRound1.setRoundTopRight(25);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_principal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_principal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_principalMouseClicked(evt);
            }
        });
        panelRound1.add(icon_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanel_cabecera.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 50, 50));

        getContentPane().add(jPanel_cabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void icon_principalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_principalMouseClicked

    }//GEN-LAST:event_icon_principalMouseClicked

    private void btn_salir2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salir2MouseClicked
        dispose();
        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_btn_salir2MouseClicked

    private void btn_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseClicked
        dispose();
        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_btn_salirMouseClicked

    private void btn_registrar_juridicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrar_juridicoMouseEntered
        panel_registrar_juridico.setBackground(new Color(80, 5, 5));
    }//GEN-LAST:event_btn_registrar_juridicoMouseEntered

    private void btn_registrar_juridicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrar_juridicoMouseExited
        panel_registrar_juridico.setBackground(new Color(81, 77, 167));
    }//GEN-LAST:event_btn_registrar_juridicoMouseExited

    private void btn_registrar_naturalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrar_naturalMouseEntered
        panel_registrar_natural.setBackground(new Color(80, 5, 5));
    }//GEN-LAST:event_btn_registrar_naturalMouseEntered

    private void btn_registrar_naturalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrar_naturalMouseExited
        panel_registrar_natural.setBackground(new Color(81, 77, 167));
    }//GEN-LAST:event_btn_registrar_naturalMouseExited

    private void btn_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseEntered
        panel_salir.setBackground(new Color(14, 120, 220));
    }//GEN-LAST:event_btn_salirMouseEntered

    private void btn_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseExited
        panel_salir.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_salirMouseExited

    private void btn_salir2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salir2MouseEntered
        panel_salir2.setBackground(new Color(14, 120, 220));
    }//GEN-LAST:event_btn_salir2MouseEntered

    private void btn_salir2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salir2MouseExited
        panel_salir2.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_salir2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_registrar_juridico;
    private javax.swing.JLabel btn_registrar_natural;
    private javax.swing.JLabel btn_salir;
    private javax.swing.JLabel btn_salir2;
    private javax.swing.JLabel icon_principal;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel_cabecera;
    private javax.swing.JPanel jPanel_juridico;
    private javax.swing.JPanel jPanel_natural;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField7;
    private prueba_diseño.PanelRound panelRound1;
    private prueba_diseño.PanelRound panelRound10;
    private prueba_diseño.PanelRound panelRound16;
    private prueba_diseño.PanelRound panelRound17;
    private prueba_diseño.PanelRound panelRound18;
    private prueba_diseño.PanelRound panelRound19;
    private prueba_diseño.PanelRound panelRound20;
    private prueba_diseño.PanelRound panelRound3;
    private prueba_diseño.PanelRound panelRound4;
    private prueba_diseño.PanelRound panelRound5;
    private prueba_diseño.PanelRound panelRound8;
    private prueba_diseño.PanelRound panelRound9;
    private prueba_diseño.PanelRound panel_registrar_juridico;
    private prueba_diseño.PanelRound panel_registrar_natural;
    private prueba_diseño.PanelRound panel_salir;
    private prueba_diseño.PanelRound panel_salir2;
    // End of variables declaration//GEN-END:variables
}
