package prueba_diseño;

import clases_conexion.BDConexion;
import clases_validacion.ValidacionesGenerales;
import static clases_validacion.ValidacionesGenerales.*;
import static clases_validacion.ValidacionesGenerales.validarNumeros;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;

public class NuevoCliente extends javax.swing.JFrame {

    public NuevoCliente() {
        initComponents();
        setSize(650, 700);
        setLocationRelativeTo(null);

        Estilos boton = new Estilos();
        boton.btnSalir(btn_salir);

        Estilos boton2 = new Estilos();
        boton2.btnSalir(btn_salir2);

        Estilos icon = new Estilos();
        icon.iconoPrincipal(icon_principal, "src/iconos32px_azul/agregar-usuario.png");

        cmb_tipo.setSelectedIndex(0);
        jPanel_natural.setVisible(true);
        jPanel_juridico.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_juridico = new javax.swing.JPanel();
        panelRound6 = new prueba_diseño.PanelRound();
        txt_nombre_juridico = new javax.swing.JTextField();
        panelRound12 = new prueba_diseño.PanelRound();
        txt_rif_juridico = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panelRound7 = new prueba_diseño.PanelRound();
        txt_direccion_juridico = new javax.swing.JTextField();
        panelRound13 = new prueba_diseño.PanelRound();
        txt_correo_juridico = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        panelRound15 = new prueba_diseño.PanelRound();
        txt_telefono_juridico = new javax.swing.JTextField();
        btnP_registrar_juridico = new prueba_diseño.PanelRound();
        btnJ_registrar_etiqueta = new javax.swing.JLabel();
        panel_salir = new prueba_diseño.PanelRound();
        btn_salir = new javax.swing.JLabel();
        jPanel_natural = new javax.swing.JPanel();
        panel_salir2 = new prueba_diseño.PanelRound();
        btn_salir2 = new javax.swing.JLabel();
        panelRound3 = new prueba_diseño.PanelRound();
        txt_correo_natural = new javax.swing.JTextField();
        panelRound4 = new prueba_diseño.PanelRound();
        txt_nombre_natural = new javax.swing.JTextField();
        panelRound5 = new prueba_diseño.PanelRound();
        txt_cedula_natural = new javax.swing.JTextField();
        panelRound8 = new prueba_diseño.PanelRound();
        txt_apellido_natural = new javax.swing.JTextField();
        panelRound9 = new prueba_diseño.PanelRound();
        txt_direccion_natural = new javax.swing.JTextField();
        panelRound10 = new prueba_diseño.PanelRound();
        txt_telefono_natural = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnP_registrar_natural = new prueba_diseño.PanelRound();
        btnN_registrar_etiqueta = new javax.swing.JLabel();
        jPanel_cabecera = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmb_tipo = new javax.swing.JComboBox<>();
        panelRound1 = new prueba_diseño.PanelRound();
        icon_principal = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_juridico.setBackground(new java.awt.Color(16, 23, 39));
        jPanel_juridico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound6.setBackground(new java.awt.Color(204, 204, 204));
        panelRound6.setRoundBottomLeft(25);
        panelRound6.setRoundBottomRight(25);
        panelRound6.setRoundTopLeft(25);
        panelRound6.setRoundTopRight(25);
        panelRound6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nombre_juridico.setBackground(new java.awt.Color(204, 204, 204));
        txt_nombre_juridico.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txt_nombre_juridico.setForeground(new java.awt.Color(0, 0, 0));
        txt_nombre_juridico.setBorder(null);
        panelRound6.add(txt_nombre_juridico, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 220, 40));

        jPanel_juridico.add(panelRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 250, 40));

        panelRound12.setBackground(new java.awt.Color(204, 204, 204));
        panelRound12.setRoundBottomLeft(25);
        panelRound12.setRoundBottomRight(25);
        panelRound12.setRoundTopLeft(25);
        panelRound12.setRoundTopRight(25);
        panelRound12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_rif_juridico.setBackground(new java.awt.Color(204, 204, 204));
        txt_rif_juridico.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txt_rif_juridico.setForeground(new java.awt.Color(0, 0, 0));
        txt_rif_juridico.setBorder(null);
        panelRound12.add(txt_rif_juridico, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 220, 40));

        jPanel_juridico.add(panelRound12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 250, 40));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Correo");
        jPanel_juridico.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cedula o Rif");
        jPanel_juridico.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nombre Empresa");
        jPanel_juridico.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Direccion");
        jPanel_juridico.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        panelRound7.setBackground(new java.awt.Color(204, 204, 204));
        panelRound7.setRoundBottomLeft(25);
        panelRound7.setRoundBottomRight(25);
        panelRound7.setRoundTopLeft(25);
        panelRound7.setRoundTopRight(25);
        panelRound7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_direccion_juridico.setBackground(new java.awt.Color(204, 204, 204));
        txt_direccion_juridico.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txt_direccion_juridico.setForeground(new java.awt.Color(0, 0, 0));
        txt_direccion_juridico.setBorder(null);
        panelRound7.add(txt_direccion_juridico, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 220, 40));

        jPanel_juridico.add(panelRound7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 250, 40));

        panelRound13.setBackground(new java.awt.Color(204, 204, 204));
        panelRound13.setRoundBottomLeft(25);
        panelRound13.setRoundBottomRight(25);
        panelRound13.setRoundTopLeft(25);
        panelRound13.setRoundTopRight(25);
        panelRound13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_correo_juridico.setBackground(new java.awt.Color(204, 204, 204));
        txt_correo_juridico.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txt_correo_juridico.setForeground(new java.awt.Color(0, 0, 0));
        txt_correo_juridico.setBorder(null);
        panelRound13.add(txt_correo_juridico, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 220, 40));

        jPanel_juridico.add(panelRound13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 250, 40));

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Telefono");
        jPanel_juridico.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        panelRound15.setBackground(new java.awt.Color(204, 204, 204));
        panelRound15.setRoundBottomLeft(25);
        panelRound15.setRoundBottomRight(25);
        panelRound15.setRoundTopLeft(25);
        panelRound15.setRoundTopRight(25);
        panelRound15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_telefono_juridico.setBackground(new java.awt.Color(204, 204, 204));
        txt_telefono_juridico.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txt_telefono_juridico.setForeground(new java.awt.Color(0, 0, 0));
        txt_telefono_juridico.setBorder(null);
        panelRound15.add(txt_telefono_juridico, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 220, 40));

        jPanel_juridico.add(panelRound15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 250, 40));

        btnP_registrar_juridico.setBackground(new java.awt.Color(81, 77, 167));
        btnP_registrar_juridico.setRoundBottomLeft(25);
        btnP_registrar_juridico.setRoundBottomRight(25);
        btnP_registrar_juridico.setRoundTopLeft(25);
        btnP_registrar_juridico.setRoundTopRight(25);
        btnP_registrar_juridico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnJ_registrar_etiqueta.setBackground(new java.awt.Color(16, 23, 39));
        btnJ_registrar_etiqueta.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnJ_registrar_etiqueta.setForeground(new java.awt.Color(255, 255, 255));
        btnJ_registrar_etiqueta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnJ_registrar_etiqueta.setText("Registrar");
        btnJ_registrar_etiqueta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnJ_registrar_etiquetaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnJ_registrar_etiquetaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnJ_registrar_etiquetaMouseExited(evt);
            }
        });
        btnP_registrar_juridico.add(btnJ_registrar_etiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 50));

        jPanel_juridico.add(btnP_registrar_juridico, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 200, 50));

        panel_salir.setBackground(new java.awt.Color(255, 255, 255));
        panel_salir.setRoundBottomLeft(25);
        panel_salir.setRoundBottomRight(25);
        panel_salir.setRoundTopLeft(25);
        panel_salir.setRoundTopRight(25);
        panel_salir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_salirMouseExited(evt);
            }
        });
        panel_salir.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanel_juridico.add(panel_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 50, 50));

        getContentPane().add(jPanel_juridico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 650, 600));

        jPanel_natural.setBackground(new java.awt.Color(16, 23, 39));
        jPanel_natural.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_salir2.setBackground(new java.awt.Color(255, 255, 255));
        panel_salir2.setRoundBottomLeft(25);
        panel_salir2.setRoundBottomRight(25);
        panel_salir2.setRoundTopLeft(25);
        panel_salir2.setRoundTopRight(25);
        panel_salir2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_salir2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_salir2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salir2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_salir2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_salir2MouseExited(evt);
            }
        });
        panel_salir2.add(btn_salir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanel_natural.add(panel_salir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 50, 50));

        panelRound3.setBackground(new java.awt.Color(204, 204, 204));
        panelRound3.setRoundBottomLeft(25);
        panelRound3.setRoundBottomRight(25);
        panelRound3.setRoundTopLeft(25);
        panelRound3.setRoundTopRight(25);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_correo_natural.setBackground(new java.awt.Color(204, 204, 204));
        txt_correo_natural.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txt_correo_natural.setForeground(new java.awt.Color(0, 0, 0));
        txt_correo_natural.setBorder(null);
        panelRound3.add(txt_correo_natural, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 220, 40));

        jPanel_natural.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 340, 250, 40));

        panelRound4.setBackground(new java.awt.Color(204, 204, 204));
        panelRound4.setRoundBottomLeft(25);
        panelRound4.setRoundBottomRight(25);
        panelRound4.setRoundTopLeft(25);
        panelRound4.setRoundTopRight(25);
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nombre_natural.setBackground(new java.awt.Color(204, 204, 204));
        txt_nombre_natural.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txt_nombre_natural.setForeground(new java.awt.Color(0, 0, 0));
        txt_nombre_natural.setBorder(null);
        panelRound4.add(txt_nombre_natural, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 220, 40));

        jPanel_natural.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 100, 250, 40));

        panelRound5.setBackground(new java.awt.Color(204, 204, 204));
        panelRound5.setRoundBottomLeft(25);
        panelRound5.setRoundBottomRight(25);
        panelRound5.setRoundTopLeft(25);
        panelRound5.setRoundTopRight(25);
        panelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_cedula_natural.setBackground(new java.awt.Color(204, 204, 204));
        txt_cedula_natural.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txt_cedula_natural.setForeground(new java.awt.Color(0, 0, 0));
        txt_cedula_natural.setBorder(null);
        panelRound5.add(txt_cedula_natural, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 220, 40));

        jPanel_natural.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 220, 250, 40));

        panelRound8.setBackground(new java.awt.Color(204, 204, 204));
        panelRound8.setRoundBottomLeft(25);
        panelRound8.setRoundBottomRight(25);
        panelRound8.setRoundTopLeft(25);
        panelRound8.setRoundTopRight(25);
        panelRound8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_apellido_natural.setBackground(new java.awt.Color(204, 204, 204));
        txt_apellido_natural.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txt_apellido_natural.setForeground(new java.awt.Color(0, 0, 0));
        txt_apellido_natural.setBorder(null);
        panelRound8.add(txt_apellido_natural, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 220, 40));

        jPanel_natural.add(panelRound8, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 100, 250, 40));

        panelRound9.setBackground(new java.awt.Color(204, 204, 204));
        panelRound9.setRoundBottomLeft(25);
        panelRound9.setRoundBottomRight(25);
        panelRound9.setRoundTopLeft(25);
        panelRound9.setRoundTopRight(25);
        panelRound9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_direccion_natural.setBackground(new java.awt.Color(204, 204, 204));
        txt_direccion_natural.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txt_direccion_natural.setForeground(new java.awt.Color(0, 0, 0));
        txt_direccion_natural.setBorder(null);
        panelRound9.add(txt_direccion_natural, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 220, 40));

        jPanel_natural.add(panelRound9, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 220, 250, 40));

        panelRound10.setBackground(new java.awt.Color(204, 204, 204));
        panelRound10.setRoundBottomLeft(25);
        panelRound10.setRoundBottomRight(25);
        panelRound10.setRoundTopLeft(25);
        panelRound10.setRoundTopRight(25);
        panelRound10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_telefono_natural.setBackground(new java.awt.Color(204, 204, 204));
        txt_telefono_natural.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txt_telefono_natural.setForeground(new java.awt.Color(0, 0, 0));
        txt_telefono_natural.setBorder(null);
        panelRound10.add(txt_telefono_natural, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 220, 40));

        jPanel_natural.add(panelRound10, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 340, 250, 40));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");
        jPanel_natural.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido");
        jPanel_natural.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cedula");
        jPanel_natural.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Direccion");
        jPanel_natural.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Telefono");
        jPanel_natural.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Correo");
        jPanel_natural.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 310, -1, -1));

        btnP_registrar_natural.setBackground(new java.awt.Color(81, 77, 167));
        btnP_registrar_natural.setForeground(new java.awt.Color(255, 255, 255));
        btnP_registrar_natural.setRoundBottomLeft(25);
        btnP_registrar_natural.setRoundBottomRight(25);
        btnP_registrar_natural.setRoundTopLeft(25);
        btnP_registrar_natural.setRoundTopRight(25);
        btnP_registrar_natural.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnN_registrar_etiqueta.setBackground(new java.awt.Color(16, 23, 39));
        btnN_registrar_etiqueta.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnN_registrar_etiqueta.setForeground(new java.awt.Color(255, 255, 255));
        btnN_registrar_etiqueta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnN_registrar_etiqueta.setText("Registrar");
        btnN_registrar_etiqueta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnN_registrar_etiquetaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnN_registrar_etiquetaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnN_registrar_etiquetaMouseExited(evt);
            }
        });
        btnP_registrar_natural.add(btnN_registrar_etiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 50));

        jPanel_natural.add(btnP_registrar_natural, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 450, 200, 50));

        getContentPane().add(jPanel_natural, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 650, 600));

        jPanel_cabecera.setBackground(new java.awt.Color(16, 23, 39));
        jPanel_cabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro Clientes");
        jPanel_cabecera.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 250, 50));

        cmb_tipo.setBackground(new java.awt.Color(204, 204, 204));
        cmb_tipo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        cmb_tipo.setForeground(new java.awt.Color(16, 23, 39));
        cmb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente Natural", "Cliente Juridico" }));
        cmb_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tipoActionPerformed(evt);
            }
        });
        jPanel_cabecera.add(cmb_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 120, -1));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(25);
        panelRound1.setRoundBottomRight(25);
        panelRound1.setRoundTopLeft(25);
        panelRound1.setRoundTopRight(25);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_principal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelRound1.add(icon_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanel_cabecera.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 50, 50));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel_cabecera.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 75, 200, -1));

        getContentPane().add(jPanel_cabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salir2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salir2MouseClicked
        dispose();
        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_btn_salir2MouseClicked

    private void btn_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseClicked
        dispose();
        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_btn_salirMouseClicked

    private void cmb_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tipoActionPerformed

        if (cmb_tipo.getSelectedIndex() == 0) {
            jPanel_natural.setVisible(true);
            jPanel_juridico.setVisible(false);
        } else if (cmb_tipo.getSelectedIndex() == 1) {
            jPanel_natural.setVisible(false);
            jPanel_juridico.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Opcion no disponibles");
        }
    }//GEN-LAST:event_cmb_tipoActionPerformed

    private void btnN_registrar_etiquetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnN_registrar_etiquetaMouseClicked
        String cedula = txt_cedula_natural.getText().trim();
        String nombre = txt_nombre_natural.getText().trim();
        String apellido = txt_apellido_natural.getText().trim();
        String direccion = txt_direccion_natural.getText().trim();
        String telefono = txt_telefono_natural.getText().trim();
        String correo = txt_correo_natural.getText().trim();
        int tipo = cmb_tipo.getSelectedIndex();

        String[] datosL = {nombre, apellido};
        String[] datosN = {telefono};
        String[] datosT = {direccion, cedula};

        if (camposVaciosArray(datosL) && camposVaciosArray(datosN) && camposVaciosArray(datosT)) {

            if (validarNumerosC(datosN) && validarLetras(datosL) && validarTodos(datosT)) {

                try {
                    Connection cn = BDConexion.conectar();
                    PreparedStatement pst = cn.prepareStatement(
                            "SELECT ci_cliente FROM clientenatural"
                            + " WHERE ci_cliente='" + cedula + "'");
                    ResultSet rs = pst.executeQuery();

                    if (rs.next()) {
                        JOptionPane.showMessageDialog(null, "Cliente Ya se encuentra registrado");

                    } else if (!rs.next()) {

                        try {
                            Connection cn3 = BDConexion.conectar();
                            PreparedStatement pst3 = cn3.prepareStatement(
                                    "insert into clientes values (?,?,?,?,?)");

                            pst3.setString(1, cedula);
                            pst3.setString(2, direccion);
                            pst3.setString(3, telefono);
                            pst3.setString(4, correo);
                            pst3.setInt(5, tipo + 1);
                            pst3.executeUpdate();

                            PreparedStatement pst2 = cn3.prepareStatement(
                                    " insert into clientenatural values (?,?,?,?)");
                            pst2.setString(1, cedula);
                            pst2.setString(2, nombre);
                            pst2.setString(3, apellido);
                            pst2.setInt(4, tipo + 1);
                            pst2.executeUpdate();

                            JOptionPane.showMessageDialog(null, "Cliente Registrado");

                            cn3.close();
                            cn.close();

                            dispose();
                            MenuPrincipal menu = new MenuPrincipal();
                            menu.setVisible(true);

                        } catch (Exception e) {
                            System.err.println(e);
                            System.err.println("Error con la Tabla Clientes");
                            JOptionPane.showMessageDialog(null, "Error al Registrar Cliente");
                        }
                    }

                } catch (Exception e) {
                    System.err.println(e);
                    JOptionPane.showMessageDialog(null, "Error al conectar a base de datos");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingreso datos Incorrectos verfique los campos");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Hay campos vacios");
        }


    }//GEN-LAST:event_btnN_registrar_etiquetaMouseClicked

    private void btnJ_registrar_etiquetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJ_registrar_etiquetaMouseClicked
        String cedula = txt_rif_juridico.getText().trim();
        String nombre = txt_nombre_juridico.getText().trim();
        String direccion = txt_direccion_juridico.getText().trim();
        String telefono = txt_telefono_juridico.getText().trim();
        String correo = txt_correo_juridico.getText().trim();
        int tipo = cmb_tipo.getSelectedIndex();

        String[] datosN = {telefono};
        String[] datosT = {direccion, cedula, nombre};

        if (camposVaciosArray(datosT) && camposVaciosArray(datosN)) {

            if (validarNumerosC(datosN) && validarTodos(datosT)) {

                try {
                    Connection cn = BDConexion.conectar();
                    PreparedStatement pst = cn.prepareStatement(
                            "SELECT rif_empresa FROM clientejuridico"
                            + " WHERE rif_empresa='" + cedula + "'");
                    ResultSet rs = pst.executeQuery();

                    if (rs.next()) {
                        JOptionPane.showMessageDialog(null, "Cliente Ya se encuentra registrado");

                    } else if (!rs.next()) {

                        try {
                            Connection cn3 = BDConexion.conectar();
                            PreparedStatement pst3 = cn3.prepareStatement(
                                    "insert into clientes values (?,?,?,?,?)");

                            pst3.setString(1, cedula);
                            pst3.setString(2, direccion);
                            pst3.setString(3, telefono);
                            pst3.setString(4, correo);
                            pst3.setInt(5, tipo + 1);
                            pst3.executeUpdate();

                            PreparedStatement pst2 = cn3.prepareStatement(
                                    " insert into clientejuridico values (?,?,?)");
                            pst2.setString(1, cedula);
                            pst2.setString(2, nombre);
                            pst2.setInt(3, tipo + 1);
                            pst2.executeUpdate();

                            JOptionPane.showMessageDialog(null, "Cliente Registrado");

                            cn3.close();
                            cn.close();

                            dispose();
                            MenuPrincipal menu = new MenuPrincipal();
                            menu.setVisible(true);

                        } catch (Exception e) {
                            System.err.println(e);
                            System.err.println("Error con la Tabla Clientes");
                            JOptionPane.showMessageDialog(null, "Error al Registrar Cliente");
                        }
                    }

                } catch (Exception e) {
                    System.err.println(e);
                    JOptionPane.showMessageDialog(null, "Error al conectar a base de datos");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingreso datos Incorrectos verfique los campos");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Hay campos vacios");
        }
    }//GEN-LAST:event_btnJ_registrar_etiquetaMouseClicked

    private void btnJ_registrar_etiquetaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJ_registrar_etiquetaMouseEntered
        btnP_registrar_juridico.setBackground(new Color(80, 5, 5));
    }//GEN-LAST:event_btnJ_registrar_etiquetaMouseEntered

    private void btnJ_registrar_etiquetaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJ_registrar_etiquetaMouseExited
        btnP_registrar_juridico.setBackground(new Color(81, 77, 167));
    }//GEN-LAST:event_btnJ_registrar_etiquetaMouseExited

    private void btnN_registrar_etiquetaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnN_registrar_etiquetaMouseEntered
        btnP_registrar_natural.setBackground(new Color(80, 5, 5));
    }//GEN-LAST:event_btnN_registrar_etiquetaMouseEntered

    private void btnN_registrar_etiquetaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnN_registrar_etiquetaMouseExited
        btnP_registrar_natural.setBackground(new Color(81, 77, 167));
    }//GEN-LAST:event_btnN_registrar_etiquetaMouseExited

    private void btn_salir2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salir2MouseEntered
        panel_salir2.setBackground(new Color(14, 120, 220));
    }//GEN-LAST:event_btn_salir2MouseEntered

    private void btn_salir2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salir2MouseExited
         panel_salir2.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_salir2MouseExited

    private void btn_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseEntered
        panel_salir.setBackground(new Color(14, 120, 220));
    }//GEN-LAST:event_btn_salirMouseEntered

    private void btn_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseExited
         panel_salir.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_salirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnJ_registrar_etiqueta;
    private javax.swing.JLabel btnN_registrar_etiqueta;
    private prueba_diseño.PanelRound btnP_registrar_juridico;
    private prueba_diseño.PanelRound btnP_registrar_natural;
    private javax.swing.JLabel btn_salir;
    private javax.swing.JLabel btn_salir2;
    private javax.swing.JComboBox<String> cmb_tipo;
    private javax.swing.JLabel icon_principal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel_cabecera;
    private javax.swing.JPanel jPanel_juridico;
    private javax.swing.JPanel jPanel_natural;
    private javax.swing.JSeparator jSeparator3;
    private prueba_diseño.PanelRound panelRound1;
    private prueba_diseño.PanelRound panelRound10;
    private prueba_diseño.PanelRound panelRound12;
    private prueba_diseño.PanelRound panelRound13;
    private prueba_diseño.PanelRound panelRound15;
    private prueba_diseño.PanelRound panelRound3;
    private prueba_diseño.PanelRound panelRound4;
    private prueba_diseño.PanelRound panelRound5;
    private prueba_diseño.PanelRound panelRound6;
    private prueba_diseño.PanelRound panelRound7;
    private prueba_diseño.PanelRound panelRound8;
    private prueba_diseño.PanelRound panelRound9;
    private prueba_diseño.PanelRound panel_salir;
    private prueba_diseño.PanelRound panel_salir2;
    private javax.swing.JTextField txt_apellido_natural;
    private javax.swing.JTextField txt_cedula_natural;
    private javax.swing.JTextField txt_correo_juridico;
    private javax.swing.JTextField txt_correo_natural;
    private javax.swing.JTextField txt_direccion_juridico;
    private javax.swing.JTextField txt_direccion_natural;
    private javax.swing.JTextField txt_nombre_juridico;
    private javax.swing.JTextField txt_nombre_natural;
    private javax.swing.JTextField txt_rif_juridico;
    private javax.swing.JTextField txt_telefono_juridico;
    private javax.swing.JTextField txt_telefono_natural;
    // End of variables declaration//GEN-END:variables
}
