/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prueba_diseño;

/**
 *
 * @author usuario
 */
public class PruebaDiseños extends javax.swing.JFrame {

    /**
     * Creates new form PruebaDiseños
     */
    public PruebaDiseños() {
        initComponents();
        setSize(800, 700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_inicio = new javax.swing.JPanel();
        panelRound4 = new prueba_diseño.PanelRound();
        panelRound13 = new prueba_diseño.PanelRound();
        empleado_icon = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txt_cantidad_proveedores7 = new javax.swing.JTextField();
        panelRound24 = new prueba_diseño.PanelRound();
        proveedor_icon = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txt_cantidad_proveedores6 = new javax.swing.JTextField();
        panelRound25 = new prueba_diseño.PanelRound();
        cliente_icon = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txt_cantidad_proveedores5 = new javax.swing.JTextField();
        panelRound14 = new prueba_diseño.PanelRound();
        proveedor_icon3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txt_cantidad_proveedores8 = new javax.swing.JTextField();
        panelRound26 = new prueba_diseño.PanelRound();
        proveedor_icon4 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txt_cantidad_proveedores9 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_inicio.setBackground(new java.awt.Color(230, 230, 230));
        jPanel_inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound4.setBackground(new java.awt.Color(250, 250, 250));
        panelRound4.setRoundBottomLeft(50);
        panelRound4.setRoundBottomRight(50);
        panelRound4.setRoundTopLeft(50);
        panelRound4.setRoundTopRight(50);
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound13.setBackground(new java.awt.Color(16, 23, 39));
        panelRound13.setRoundBottomLeft(50);
        panelRound13.setRoundBottomRight(50);
        panelRound13.setRoundTopLeft(50);
        panelRound13.setRoundTopRight(50);
        panelRound13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        empleado_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelRound13.add(empleado_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 40, 40));

        jLabel29.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(81, 77, 167));
        jLabel29.setText("Empleados");
        panelRound13.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jLabel30.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(81, 77, 167));
        jLabel30.setText("Total Registrados");
        panelRound13.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        txt_cantidad_proveedores7.setBackground(new java.awt.Color(255, 255, 255));
        txt_cantidad_proveedores7.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txt_cantidad_proveedores7.setForeground(new java.awt.Color(0, 0, 0));
        txt_cantidad_proveedores7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cantidad_proveedores7.setText("8");
        txt_cantidad_proveedores7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidad_proveedores7ActionPerformed(evt);
            }
        });
        panelRound13.add(txt_cantidad_proveedores7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 100, 50));

        panelRound4.add(panelRound13, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 30, 230, 250));

        panelRound24.setBackground(new java.awt.Color(16, 23, 39));
        panelRound24.setRoundBottomLeft(50);
        panelRound24.setRoundBottomRight(50);
        panelRound24.setRoundTopLeft(50);
        panelRound24.setRoundTopRight(50);
        panelRound24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        proveedor_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelRound24.add(proveedor_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 40, 40));

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(81, 77, 167));
        jLabel19.setText("Proveedores");
        panelRound24.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel28.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(81, 77, 167));
        jLabel28.setText("Total Registrados");
        panelRound24.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        txt_cantidad_proveedores6.setBackground(new java.awt.Color(255, 255, 255));
        txt_cantidad_proveedores6.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txt_cantidad_proveedores6.setForeground(new java.awt.Color(0, 0, 0));
        txt_cantidad_proveedores6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cantidad_proveedores6.setText("8");
        txt_cantidad_proveedores6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidad_proveedores6ActionPerformed(evt);
            }
        });
        panelRound24.add(txt_cantidad_proveedores6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 100, 50));

        panelRound4.add(panelRound24, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 30, 230, 250));

        panelRound25.setBackground(new java.awt.Color(16, 23, 39));
        panelRound25.setRoundBottomLeft(50);
        panelRound25.setRoundBottomRight(50);
        panelRound25.setRoundTopLeft(50);
        panelRound25.setRoundTopRight(50);
        panelRound25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cliente_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelRound25.add(cliente_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 40, 40));

        jLabel26.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(81, 77, 167));
        jLabel26.setText("Clientes");
        panelRound25.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jLabel27.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(81, 77, 167));
        jLabel27.setText("Total Registrados");
        panelRound25.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        txt_cantidad_proveedores5.setBackground(new java.awt.Color(255, 255, 255));
        txt_cantidad_proveedores5.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txt_cantidad_proveedores5.setForeground(new java.awt.Color(0, 0, 0));
        txt_cantidad_proveedores5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cantidad_proveedores5.setText("8");
        txt_cantidad_proveedores5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidad_proveedores5ActionPerformed(evt);
            }
        });
        panelRound25.add(txt_cantidad_proveedores5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 100, 50));

        panelRound4.add(panelRound25, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 30, 230, 250));

        panelRound14.setBackground(new java.awt.Color(16, 23, 39));
        panelRound14.setRoundBottomLeft(50);
        panelRound14.setRoundBottomRight(50);
        panelRound14.setRoundTopLeft(50);
        panelRound14.setRoundTopRight(50);
        panelRound14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        proveedor_icon3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelRound14.add(proveedor_icon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 40, 40));

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(81, 77, 167));
        jLabel20.setText("Ventas");
        panelRound14.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel31.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(81, 77, 167));
        jLabel31.setText("Total Registrados");
        panelRound14.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        txt_cantidad_proveedores8.setBackground(new java.awt.Color(255, 255, 255));
        txt_cantidad_proveedores8.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txt_cantidad_proveedores8.setForeground(new java.awt.Color(0, 0, 0));
        txt_cantidad_proveedores8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cantidad_proveedores8.setText("8");
        txt_cantidad_proveedores8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidad_proveedores8ActionPerformed(evt);
            }
        });
        panelRound14.add(txt_cantidad_proveedores8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 100, 50));

        panelRound4.add(panelRound14, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 300, 230, 250));

        panelRound26.setBackground(new java.awt.Color(16, 23, 39));
        panelRound26.setRoundBottomLeft(50);
        panelRound26.setRoundBottomRight(50);
        panelRound26.setRoundTopLeft(50);
        panelRound26.setRoundTopRight(50);
        panelRound26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        proveedor_icon4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelRound26.add(proveedor_icon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 40, 40));

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(81, 77, 167));
        jLabel23.setText("Productos");
        panelRound26.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jLabel32.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(81, 77, 167));
        jLabel32.setText("Total Registrados");
        panelRound26.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        txt_cantidad_proveedores9.setBackground(new java.awt.Color(255, 255, 255));
        txt_cantidad_proveedores9.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txt_cantidad_proveedores9.setForeground(new java.awt.Color(0, 0, 0));
        txt_cantidad_proveedores9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cantidad_proveedores9.setText("8");
        txt_cantidad_proveedores9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidad_proveedores9ActionPerformed(evt);
            }
        });
        panelRound26.add(txt_cantidad_proveedores9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 100, 50));

        panelRound4.add(panelRound26, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 300, 230, 250));

        jPanel_inicio.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 780, 575));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(16, 23, 39));
        jLabel14.setText("Fecha - Hora");
        jPanel_inicio.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, -1, -1));

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(81, 77, 167));
        jLabel15.setText("Inicio - Resumen de Datos");
        jPanel_inicio.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cantidad_proveedores5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidad_proveedores5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidad_proveedores5ActionPerformed

    private void txt_cantidad_proveedores6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidad_proveedores6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidad_proveedores6ActionPerformed

    private void txt_cantidad_proveedores7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidad_proveedores7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidad_proveedores7ActionPerformed

    private void txt_cantidad_proveedores8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidad_proveedores8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidad_proveedores8ActionPerformed

    private void txt_cantidad_proveedores9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidad_proveedores9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidad_proveedores9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaDiseños.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaDiseños.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaDiseños.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaDiseños.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruebaDiseños().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cliente_icon;
    private javax.swing.JLabel empleado_icon;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel_inicio;
    private prueba_diseño.PanelRound panelRound13;
    private prueba_diseño.PanelRound panelRound14;
    private prueba_diseño.PanelRound panelRound24;
    private prueba_diseño.PanelRound panelRound25;
    private prueba_diseño.PanelRound panelRound26;
    private prueba_diseño.PanelRound panelRound4;
    private javax.swing.JLabel proveedor_icon;
    private javax.swing.JLabel proveedor_icon3;
    private javax.swing.JLabel proveedor_icon4;
    private javax.swing.JTextField txt_cantidad_proveedores5;
    private javax.swing.JTextField txt_cantidad_proveedores6;
    private javax.swing.JTextField txt_cantidad_proveedores7;
    private javax.swing.JTextField txt_cantidad_proveedores8;
    private javax.swing.JTextField txt_cantidad_proveedores9;
    // End of variables declaration//GEN-END:variables
}
